# docker-compose.yml
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:aarch64
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
    ports:
      - 3080:80
      - 3012:3012
